# Generated by Django 4.0.3 on 2022-04-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromemo', '0007_alter_document_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
