# Generated by Django 4.0.3 on 2022-04-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromemo', '0008_directory_slug_alter_directory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='slug',
            field=models.SlugField(),
        ),
    ]
