# Generated by Django 4.0.3 on 2022-04-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromemo', '0009_alter_directory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='title',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
