# Generated by Django 4.0.3 on 2022-04-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromemo', '0010_alter_directory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
