# Generated by Django 4.0.3 on 2022-04-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micromemo', '0011_alter_directory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
