# Generated by Django 4.0.3 on 2022-05-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromemo', '0015_remove_directory_slug_alter_directory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
