# Generated by Django 4.0.3 on 2022-05-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromemo', '0016_alter_directory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
