# Generated by Django 4.0.3 on 2022-05-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromemo', '0017_alter_document_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
